# Generated by Django 4.2.5 on 2023-10-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='country_code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
