# Generated by Django 4.2.5 on 2023-10-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofilemodel_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], max_length=1),
        ),
    ]
