# Generated by Django 4.2.5 on 2023-10-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofilemodel_occupation_others_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='occupation_others',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
