# Generated by Django 4.2.5 on 2023-10-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_question_choice'),
        ('users', '0006_userprofilemodel_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofilemodel')),
            ],
        ),
    ]
