# Generated by Django 4.2.5 on 2023-11-01 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_modulesmediafile_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_attemptedassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.modulemodel')),
                ('modulemediafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.modulesmediafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
