# Generated by Django 4.2.5 on 2023-11-04 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_modulesmediafile_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_reassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReAssessmentAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassessment_date', models.DateField(auto_now_add=True)),
                ('average', models.DecimalField(decimal_places=2, max_digits=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.modulemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
