# Generated by Django 4.2.5 on 2023-11-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_reassessmentaverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassessmentaverage',
            name='average',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
