# Generated by Django 4.2.5 on 2023-11-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_reassessmentaverage_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassessmentaverage',
            name='average',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
