# Generated by Django 4.2.5 on 2023-11-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofilemodel_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images/'),
        ),
    ]
