# Generated by Django 4.2.5 on 2023-11-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_userprofilemodel_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='user_profile_images/'),
        ),
    ]
