# Generated by Django 4.2.5 on 2023-11-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userprofilemodel_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='profile_image',
            new_name='profile_img',
        ),
    ]
