# Generated by Django 4.2.5 on 2023-09-28 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255)),
                ('total_modules', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter only numbers', regex='^[1-9][0-9]*$')])),
                ('version', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cover_image', models.ImageField(max_length=255, upload_to='course_cover_images/')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
