# Generated by Django 4.2.5 on 2023-09-30 07:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulesMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='modules_media/')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=255)),
                ('order', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter only numbers', regex='^[1-9][0-9]*$')])),
                ('duration_hours', models.CharField(max_length=10)),
                ('duration_minutes', models.CharField(max_length=10)),
                ('module_type', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Document', 'Document')], max_length=255)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='courses.coursemodel')),
                ('module_media_files', models.ManyToManyField(to='courses.modulesmediafile')),
            ],
        ),
    ]
