# Generated by Django 4.2.5 on 2023-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_modulesmediafile_modulemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulemodel',
            name='module_type',
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='module_type',
            field=models.ManyToManyField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Document', 'Document')], to='courses.modulemodel'),
        ),
    ]
