# Generated by Django 4.2.5 on 2023-09-30 09:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_modulemodel_module_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulemodel',
            name='module_type',
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='module_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Document', 'Document')], max_length=100), default=None, size=None),
        ),
    ]
