# Generated by Django 4.2.5 on 2023-10-03 04:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_modulemodel_module_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulemodel',
            name='module_media_files',
        ),
        migrations.AddField(
            model_name='modulesmediafile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 3, 4, 25, 11, 449071, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulesmediafile',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.modulemodel'),
        ),
    ]
