# Generated by Django 4.2.5 on 2023-10-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_modulemodel_module_media_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulemodel',
            name='course',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='courses.coursemodel'),
        ),
    ]
