# Generated by Django 4.2.5 on 2023-10-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_modulemodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulesmediafile',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.modulemodel'),
        ),
    ]
