# Generated by Django 4.2.5 on 2023-10-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_modulesmediafile_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulemodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.coursemodel'),
        ),
    ]
