# Generated by Django 4.2.5 on 2023-10-12 11:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='course_expertise',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='flag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Trending', 'Trending')], max_length=100), null=True, size=None),
        ),
    ]
