# Generated by Django 4.2.5 on 2023-10-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_duration_hours_modulemodel_duration_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_show_time', models.CharField(blank=True, max_length=255, null=True)),
                ('popup_question_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.modulemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PopupChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_choice_text', models.TextField()),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('popup_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.popupquestion')),
            ],
        ),
    ]
