# Generated by Django 4.2.5 on 2023-11-10 07:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0014_alter_modulesmediafile_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemodel',
            name='material_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='flag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Trending', 'Trending'), ('Upselling', 'Upselling')], max_length=100), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
