# Generated by Django 4.2.5 on 2023-11-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_subscription_user_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesmediafile',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulesmediafile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='modules_media/'),
        ),
    ]
